using System;
using System.Globalization;
using LaTeXSnipper.OfficePlugin.Abstractions;

namespace LaTeXSnipper.OfficePlugin.WordAddIn;

public static class WordAddInText
{
    public static string GetExceptionMessage(Exception exception)
    {
        return OfficeOperationError.Describe(exception);
    }

    public static string Get(string key)
    {
        if (key == "ToMathTypeButton" || key == "ToMathTypeTip" || key.StartsWith("MathType", StringComparison.Ordinal))
            return MathTypeText.Get(key);
        bool zh = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "zh";
        return zh ? GetZh(key) : GetEn(key);
    }

    private static string GetEn(string key)
    {
        return key switch
        {
            "RibbonTab" => "LaTeXSnipper",
            "FormulaGroup" => "Formula",
            "EditGroup" => "Edit",
            "NumberingGroup" => "Numbering",
            "ToolsGroup" => "Tools",
            "InsertInlineButton" => "Inline Formula",
            "InsertDisplayButton" => "Display Formula",
            "InsertNumberedButton" => "Numbered Formula",
            "ScreenshotOcrButton" => "Screenshot OCR",
            "CancelOcrButton" => "Cancel OCR",
            "AutoNumberButton" => "Add Number",
            "RenumberButton" => "Renumber All",
            "HelpButton" => "Help",
            "SettingsButton" => "Settings",
            "ShowTaskPaneButton" => "Status Pane",
            "LoadSelectedButton" => "Load Selected",
            "DeleteSelectedButton" => "Delete Selected",
            "OfficePluginLabel" => "Office plugin",
            "EquationLabel" => "Equation",
            "DisplayOption" => "Display equation",
            "AutoNumberOption" => "Auto number",
            "ManualNumberPlaceholder" => "Custom number",
            "ConnectButton" => "Connect",
            "InsertInlineTip" => "Insert an inline Word equation.",
            "InsertDisplayTip" => "Insert a centered display equation.",
            "InsertNumberedTip" => "Insert a numbered display equation.",
            "ScreenshotOcrTip" => "Wait for screenshot OCR; click again to cancel.",
            "AutoNumberTip" => "Add an automatic number to the selected display formula.",
            "RenumberTip" => "Renumber all automatically numbered formulas in document order.",
            "HelpTip" => "View plugin help.",
            "SettingsTip" => "Open LaTeXSnipper settings.",
            "ShowTaskPaneTip" => "Show the status pane.",
            "LoadSelectedTip" => "Load the selected formula into the editor.",
            "DeleteSelectedTip" => "Delete selected formulas.",
            "EditorInsert" => "Insert",
            "EditorUpdate" => "Update",
            "Cancel" => "Cancel",
            "ErrorTitle" => "LaTeXSnipper",
            "SelectedFormulaRequired" => "Select a formula first.",
            "SelectedFormulaMetadataMissing" => "The selected formula metadata could not be found.",
            "InsertInsideFormulaError" => "Place the cursor outside the formula before inserting another formula.",
            "InsertInsideNumberedFormulaError" => "Place the cursor outside the formula before inserting another formula.",
            "TaskPaneTitle" => "LaTeXSnipper",
            "TaskPaneActions" => "Actions",
            "ReadyStatus" => "Ready.",
            "WorkingStatus" => "Working...",
            "BoundaryInsertedStatus" => "Numbering separator inserted.",
            "EditorReadyStatus" => "Editor ready.",
            "OmmlInsertingStatus" => "Inserting Word OMML formula object.",
            "OleInsertingStatus" => "Inserting LaTeXSnipper OLE formula object.",
            "CommandTimeoutStatus" => "Office command timed out. The document was left unchanged if the operation had not reached Word yet.",
            "OleInsertedStatus" => "Inserted OLE equation.",
            "OmmlInsertedStatus" => "Inserted OMML equation.",
            "UpdatedStatus" => "Updated equation in Word.",
            "UnchangedStatus" => "Equation unchanged.",
            "DeletedStatus" => "Deleted selected formula.",
            "LoadedStatus" => "Loaded selected equation.",
            "OcrWaitingStatus" => "Waiting for screenshot OCR.",
            "OcrRecognizingStatus" => "Recognizing screenshot formula.",
            "OcrCanceledStatus" => "Screenshot OCR canceled.",
            "OcrLoadedStatus" => "Screenshot OCR result loaded.",
            "AutoNumberedStatus" => "Added a number to the selected equation.",
            "RenumberedStatus" => "Renumbered {count} equations.",
            "RenumberedWithSkippedStatus" => "Renumbered {count} equations; skipped {metadataSkipped} formulas with missing metadata and {numberingSkipped} formulas with incomplete numbering fields.",
            "NoNumberedStatus" => "No automatically numbered equations found.",
            "AlreadyNumberedStatus" => "Selected equation already has numbering.",
            "AutoNumberDisplayOnlyStatus" => "Add Number only applies to unnumbered display equations.",
            "EditingFormulaTitle" => "Editing Formula",
            "HelpStatus" => "Help opened.",
            "SettingsStatus" => "Settings opened.",
            "SettingsTitle" => "LaTeXSnipper Word Plugin Settings",
            "SettingsNumberingGroup" => "Default numbered formula layout",
            "SettingsNumberRight" => "Number on the right",
            "SettingsNumberLeft" => "Number on the left",
            "TaskPaneShownStatus" => "Status pane shown.",
            "ConnectedAutomationStatus" => "Connected to LaTeXSnipper Automation API.",
            "AutomationOcrAlreadyWaiting" => "Screenshot OCR is busy. Wait a moment and try again.",
            "ConversionGroup" => "Conversion",
            "ReferenceGroup" => "Cross Reference",
            "BoundaryGroup" => "Numbering Boundaries",
            "FormattingGroup" => "Formula Style",
            "ParsingGroup" => "Formula Parsing",
            "ToOleButton" => "Convert to OLE",
            "ToOmmlButton" => "Convert to Word",
            "ToOleSelectedTip" => "Convert selected Word or MathType equations to plugin OLE formulas.",
            "ToOmmlSelectedTip" => "Convert selected formulas to native Word equations.",
            "InsertReferenceButton" => "Insert Reference",
            "InsertReferenceTip" => "Insert a placeholder, then click a numbered formula.",
            "InsertChapterBoundaryButton" => "Chapter Separator",
            "InsertSectionBoundaryButton" => "Section Boundary",
            "InsertChapterBoundaryTip" => "Mark the start of a chapter for automatic numbering.",
            "InsertSectionBoundaryTip" => "Mark the start of a section for automatic numbering.",
            "FormatSelectedButton" => "Format Selected",
            "FormatAllButton" => "Format All",
            "FormatSelectedTip" => "Reset selected formulas to the default style and natural size.",
            "FormatAllTip" => "Reset all plugin formulas to the default style and natural size.",
            "ParseSelectedButton" => "Parse Selected",
            "ParseAllButton" => "Parse All",
            "ParseSelectedTip" => "Convert delimited LaTeX in the selection to formulas.",
            "ParseAllTip" => "Convert delimited LaTeX in the document body and tables to formulas.",
            "ReferencePlaceholderText" => "[Select a formula]",
            "ReferencePlaceholderStatus" => "Select a numbered formula to complete the reference.",
            "ReferenceInsertedStatus" => "Inserted formula reference.",
            "ChapterBoundaryText" => "Chapter separator",
            "SectionBoundaryText" => "Section boundary",
            "ConvertedStatus" => "Converted {count} formulas.",
            "ConvertedWithSkippedStatus" => "Converted {count} formulas; skipped {skipped} missing formulas.",
            "ConvertedWithFailuresStatus" => "Processed {total} formulas: converted {succeeded}, failed {failed}, skipped {skipped}. First error: {reason}",
            "NoConversionTargetsStatus" => "No formulas to convert were found.",
            "NoConversionNeededStatus" => "The selected formulas already use the target format.",
            "FormattedStatus" => "Formatted {count} formulas.",
            "FormattedWithSkippedStatus" => "Formatted {count} formulas; skipped {skipped} missing formulas.",
            "FormattedWithFailuresStatus" => "Processed {total} formulas: formatted {succeeded}, failed {failed}, skipped {skipped}. First error: {reason}",
            "NoFormattingTargetsStatus" => "No formulas to format were found.",
            "NoFormattingNeededStatus" => "The selected formulas already use the default style.",
            "BatchConvertingStatus" => "Converting formulas: {processed}/{total}.",
            "BatchFormattingStatus" => "Formatting formulas: {processed}/{total}.",
            "BatchParsingStatus" => "Parsing formulas: {processed}/{total}.",
            "NoParsingTargetsStatus" => "No formulas to parse were found.",
            "ParsedStatus" => "Parsed {count} formulas.",
            "ParsedWithFailuresStatus" => "Processed {total} formulas: {succeeded} succeeded, {failed} failed. First error: {reason}",
            "InvalidParsingSourceStatus" => "The LaTeX delimiter or equation tag is incomplete.",
            "ParseSourceChangedError" => "The source text changed before it could be parsed.",
            _ => key,
        };
    }

    private static string GetZh(string key)
    {
        return key switch
        {
            "RibbonTab" => "LaTeXSnipper",
            "FormulaGroup" => "公式",
            "EditGroup" => "编辑",
            "NumberingGroup" => "编号",
            "ToolsGroup" => "工具",
            "InsertInlineButton" => "行内公式",
            "InsertDisplayButton" => "行间公式",
            "InsertNumberedButton" => "带编号公式",
            "ScreenshotOcrButton" => "截图识别",
            "CancelOcrButton" => "取消识别",
            "AutoNumberButton" => "添加编号",
            "RenumberButton" => "重编号",
            "HelpButton" => "帮助",
            "SettingsButton" => "设置",
            "ShowTaskPaneButton" => "状态窗格",
            "LoadSelectedButton" => "加载所选",
            "DeleteSelectedButton" => "删除所选",
            "OfficePluginLabel" => "Office 插件",
            "EquationLabel" => "公式",
            "DisplayOption" => "行间公式",
            "AutoNumberOption" => "自动编号",
            "ManualNumberPlaceholder" => "自定义编号",
            "ConnectButton" => "连接",
            "InsertInlineTip" => "插入行内公式。",
            "InsertDisplayTip" => "插入行间公式。",
            "InsertNumberedTip" => "插入带编号的行间公式。",
            "ScreenshotOcrTip" => "等待截图识别结果，再次点击取消。",
            "AutoNumberTip" => "为选中的行间公式添加自动编号。",
            "RenumberTip" => "重排所有自动编号的公式。",
            "HelpTip" => "查看插件帮助。",
            "SettingsTip" => "打开 LaTeXSnipper 设置。",
            "ShowTaskPaneTip" => "显示状态窗格。",
            "LoadSelectedTip" => "将所选公式加载到编辑器。",
            "DeleteSelectedTip" => "删除所选公式。",
            "EditorInsert" => "插入",
            "EditorUpdate" => "更新",
            "Cancel" => "取消",
            "ErrorTitle" => "LaTeXSnipper",
            "SelectedFormulaRequired" => "请先选择一个 LaTeXSnipper 公式。",
            "SelectedFormulaMetadataMissing" => "无法找到所选公式的元数据。",
            "InsertInsideFormulaError" => "请将光标移到公式外，再插入其他公式。",
            "InsertInsideNumberedFormulaError" => "请将光标移到公式外，再插入其他公式。",
            "TaskPaneTitle" => "LaTeXSnipper",
            "TaskPaneActions" => "操作",
            "ReadyStatus" => "就绪。",
            "WorkingStatus" => "处理中...",
            "BoundaryInsertedStatus" => "编号分隔符已插入。",
            "EditorReadyStatus" => "编辑器已就绪。",
            "OmmlInsertingStatus" => "正在插入 Word OMML 公式对象。",
            "OleInsertingStatus" => "正在插入 LaTeXSnipper OLE 公式对象。",
            "CommandTimeoutStatus" => "Office 命令超时。若操作尚未写入 Word，文档已保持不变。",
            "OleInsertedStatus" => "已插入 OLE 公式。",
            "OmmlInsertedStatus" => "已插入 OMML 公式。",
            "UpdatedStatus" => "已更新公式。",
            "UnchangedStatus" => "公式未更改。",
            "DeletedStatus" => "已删除所选公式。",
            "LoadedStatus" => "已加载所选公式。",
            "OcrWaitingStatus" => "正在等待截图识别；请使用全局快捷键后框选公式区域。",
            "OcrRecognizingStatus" => "正在识别截图公式。",
            "OcrCanceledStatus" => "已取消截图识别。",
            "OcrLoadedStatus" => "截图识别结果已加载。",
            "AutoNumberedStatus" => "已为所选公式添加编号。",
            "RenumberedStatus" => "已重排 {count} 个公式编号。",
            "RenumberedWithSkippedStatus" => "已重排 {count} 个公式编号，跳过 {metadataSkipped} 个缺失元数据、{numberingSkipped} 个编号字段不完整的公式。",
            "NoNumberedStatus" => "未找到自动编号公式。",
            "AlreadyNumberedStatus" => "所选公式已有编号。",
            "AutoNumberDisplayOnlyStatus" => "添加编号只适用于未编号的行间公式。",
            "EditingFormulaTitle" => "正在编辑公式",
            "HelpStatus" => "已打开帮助。",
            "SettingsStatus" => "已打开设置。",
            "SettingsTitle" => "LaTeXSnipper Word 插件设置",
            "SettingsNumberingGroup" => "带编号公式默认布局",
            "SettingsNumberRight" => "编号在右侧",
            "SettingsNumberLeft" => "编号在左侧",
            "TaskPaneShownStatus" => "状态窗格已显示。",
            "ConnectedAutomationStatus" => "已连接到 LaTeXSnipper Automation API。",
            "AutomationOcrAlreadyWaiting" => "截图识别正忙，请稍后再试。",
            "ConversionGroup" => "转换",
            "ReferenceGroup" => "交叉引用",
            "BoundaryGroup" => "编号边界",
            "FormattingGroup" => "公式样式",
            "ParsingGroup" => "公式解析",
            "ToOleButton" => "转为 OLE",
            "ToOmmlButton" => "转为 Word",
            "ToOleSelectedTip" => "将所选 Word 或 MathType 公式转为插件 OLE 公式。",
            "ToOmmlSelectedTip" => "将所选公式转为 Word 原生公式。",
            "InsertReferenceButton" => "插入引用",
            "InsertReferenceTip" => "插入占位符，再单击带编号公式。",
            "InsertChapterBoundaryButton" => "章分隔符",
            "InsertSectionBoundaryButton" => "节分隔符",
            "InsertChapterBoundaryTip" => "标记自动编号的新章节起点。",
            "InsertSectionBoundaryTip" => "标记自动编号的新节起点。",
            "FormatSelectedButton" => "格式化所选",
            "FormatAllButton" => "格式化全文",
            "FormatSelectedTip" => "恢复所选公式的默认样式和自然大小。",
            "FormatAllTip" => "恢复全文插件公式的默认样式和自然大小。",
            "ParseSelectedButton" => "解析所选",
            "ParseAllButton" => "解析全文",
            "ParseSelectedTip" => "将选区内带定界符的 LaTeX 转为公式。",
            "ParseAllTip" => "将正文及表格中带定界符的 LaTeX 转为公式。",
            "ReferencePlaceholderText" => "[请选择公式]",
            "ReferencePlaceholderStatus" => "请选择一个带编号公式以完成引用。",
            "ReferenceInsertedStatus" => "已插入公式引用。",
            "ChapterBoundaryText" => "章分隔符",
            "SectionBoundaryText" => "节分隔符",
            "ConvertedStatus" => "已转换 {count} 个公式。",
            "ConvertedWithSkippedStatus" => "已转换 {count} 个公式，跳过 {skipped} 个已不存在的公式。",
            "ConvertedWithFailuresStatus" => "共处理 {total} 个公式：成功转换 {succeeded} 个，失败 {failed} 个，跳过 {skipped} 个。首个错误：{reason}",
            "NoConversionTargetsStatus" => "未找到可转换的公式。",
            "NoConversionNeededStatus" => "所选公式已经是目标格式。",
            "FormattedStatus" => "已格式化 {count} 个公式。",
            "FormattedWithSkippedStatus" => "已格式化 {count} 个公式，跳过 {skipped} 个已不存在的公式。",
            "FormattedWithFailuresStatus" => "共处理 {total} 个公式：成功格式化 {succeeded} 个，失败 {failed} 个，跳过 {skipped} 个。首个错误：{reason}",
            "NoFormattingTargetsStatus" => "未找到可格式化的公式。",
            "NoFormattingNeededStatus" => "所选公式已经是默认样式。",
            "BatchConvertingStatus" => "正在转换公式：{processed}/{total}。",
            "BatchFormattingStatus" => "正在格式化公式：{processed}/{total}。",
            "BatchParsingStatus" => "正在解析公式：{processed}/{total}。",
            "NoParsingTargetsStatus" => "未找到可解析的公式。",
            "ParsedStatus" => "已解析 {count} 个公式。",
            "ParsedWithFailuresStatus" => "共处理 {total} 个公式，成功 {succeeded} 个，失败 {failed} 个。首个错误：{reason}",
            "InvalidParsingSourceStatus" => "LaTeX 定界符或公式编号标记不完整。",
            "ParseSourceChangedError" => "源文本在解析前已发生变化。",
            _ => key,
        };
    }
}
