using System.Globalization;

namespace LaTeXSnipper.OfficePlugin.WordAddIn;

public static class WordAddInText
{
    public static string Get(string key)
    {
        bool zh = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "zh";
        return zh ? GetZh(key) : GetEn(key);
    }

    private static string GetEn(string key)
    {
        return key switch
        {
            "RibbonTab" => "LaTeXSnipper",
            "FormulaGroup" => "Formula",
            "EditGroup" => "Edit",
            "NumberingGroup" => "Numbering",
            "ToolsGroup" => "Tools",
            "InsertOmmlButton" => "Insert OMML",
            "InsertInlineButton" => "Inline Formula",
            "InsertDisplayButton" => "Display Formula",
            "InsertNumberedButton" => "Numbered Formula",
            "ScreenshotOcrButton" => "Screenshot OCR",
            "CancelOcrButton" => "Cancel OCR",
            "AutoNumberButton" => "Auto Number",
            "RenumberButton" => "Renumber All",
            "HelpButton" => "Help",
            "SettingsButton" => "Settings",
            "ShowTaskPaneButton" => "Status Pane",
            "LoadSelectedButton" => "Load Selected",
            "DeleteSelectedButton" => "Delete Selected",
            "OfficePluginLabel" => "Office plugin",
            "EquationLabel" => "Equation",
            "DisplayOption" => "Display equation",
            "AutoNumberOption" => "Auto number",
            "ManualNumberPlaceholder" => "Custom number",
            "ConnectButton" => "Connect",
            "InsertOmmlTip" => "Insert the current formula as native Word OMML.",
            "InsertInlineTip" => "Insert the current LaTeX as an inline Word equation.",
            "InsertDisplayTip" => "Insert the current LaTeX as a centered display equation.",
            "InsertNumberedTip" => "Insert the current LaTeX as an automatically numbered display equation.",
            "ScreenshotOcrTip" => "Wait for the next LaTeXSnipper global-hotkey capture; click again to cancel.",
            "AutoNumberTip" => "Add automatic numbering to the selected LaTeXSnipper formula.",
            "RenumberTip" => "Renumber all automatically numbered LaTeXSnipper formulas in document order.",
            "HelpTip" => "Show LaTeXSnipper Office plugin help.",
            "SettingsTip" => "Configure Office plugin shortcuts and numbering defaults.",
            "ShowTaskPaneTip" => "Show the LaTeXSnipper status pane.",
            "LoadSelectedTip" => "Load the selected LaTeXSnipper formula.",
            "DeleteSelectedTip" => "Delete the selected LaTeXSnipper formula and its metadata.",
            "EditorInsert" => "Insert",
            "EditorUpdate" => "Update",
            "Cancel" => "Cancel",
            "ErrorTitle" => "LaTeXSnipper",
            "SelectedFormulaRequired" => "Select a LaTeXSnipper formula first.",
            "SelectedFormulaMetadataMissing" => "The selected formula metadata could not be found.",
            "InsertInsideFormulaError" => "Place the cursor outside the LaTeXSnipper equation before inserting another formula.",
            "InsertInsideNumberedFormulaError" => "Place the cursor outside the numbered LaTeXSnipper equation before inserting another formula.",
            "TaskPaneTitle" => "LaTeXSnipper",
            "TaskPaneActions" => "Actions",
            "ReadyStatus" => "Ready.",
            "WorkingStatus" => "Working...",
            "EditorReadyStatus" => "Editor ready.",
            "ConvertingStatus" => "Converting LaTeX through the desktop Bridge.",
            "InsertedStatus" => "Inserted equation into Word.",
            "UpdatedStatus" => "Updated equation in Word.",
            "DeletedStatus" => "Deleted selected equation.",
            "LoadedStatus" => "Loaded selected equation.",
            "OcrWaitingStatus" => "Waiting for screenshot OCR. Use the global shortcut, then capture a formula region.",
            "OcrCanceledStatus" => "Screenshot OCR canceled.",
            "OcrLoadedStatus" => "Screenshot OCR result loaded.",
            "AutoNumberedStatus" => "Added automatic numbering to selected equation.",
            "RenumberedStatus" => "Renumbered {count} equations.",
            "NoNumberedStatus" => "No automatically numbered equations found.",
            "AlreadyNumberedStatus" => "Selected equation already has numbering.",
            "EditingFormulaTitle" => "Editing Formula",
            "HelpStatus" => "Help opened in Word.",
            "SettingsStatus" => "Settings opened.",
            "SettingsTitle" => "LaTeXSnipper Office Plugin Settings",
            "SettingsNumberingGroup" => "Default numbered formula layout",
            "SettingsNumberRight" => "Number on the right",
            "SettingsNumberLeft" => "Number on the left",
            "SettingsShortcuts" => "Ribbon KeyTips\r\n- Alt, LS, I: Inline Formula.\r\n- Alt, LS, D: Display Formula.\r\n- Alt, LS, N: Numbered Formula.\r\n- Alt, LS, O: Screenshot OCR.\r\n- Alt, LS, L: Load Selected.\r\n- Alt, LS, X: Delete Selected.\r\n- Alt, LS, A: Auto Number.\r\n- Alt, LS, R: Renumber All.\r\n- Alt, LS, P: Status Pane.\r\n- Alt, LS, S: Settings.\r\n- Alt, LS, H: Help.\r\n\r\nEditor keyboard\r\n- Ctrl+Enter: insert a line break in the editor.\r\n- Esc: close the editor without applying changes.",
            "TaskPaneShownStatus" => "Status pane shown.",
            "ConnectedBridgeStatus" => "Connected to LaTeXSnipper.",
            _ => key,
        };
    }

    private static string GetZh(string key)
    {
        return key switch
        {
            "RibbonTab" => "LaTeXSnipper",
            "FormulaGroup" => "公式",
            "EditGroup" => "编辑",
            "NumberingGroup" => "编号",
            "ToolsGroup" => "工具",
            "InsertOmmlButton" => "插入 OMML",
            "InsertInlineButton" => "行内公式",
            "InsertDisplayButton" => "行间公式",
            "InsertNumberedButton" => "带编号公式",
            "ScreenshotOcrButton" => "截图识别",
            "CancelOcrButton" => "取消识别",
            "AutoNumberButton" => "自动编号",
            "RenumberButton" => "重编号",
            "HelpButton" => "帮助",
            "SettingsButton" => "设置",
            "ShowTaskPaneButton" => "状态窗格",
            "LoadSelectedButton" => "加载所选",
            "DeleteSelectedButton" => "删除所选",
            "OfficePluginLabel" => "Office 插件",
            "EquationLabel" => "公式",
            "DisplayOption" => "行间公式",
            "AutoNumberOption" => "自动编号",
            "ManualNumberPlaceholder" => "自定义编号",
            "ConnectButton" => "连接",
            "InsertOmmlTip" => "将当前公式插入为 Word 原生 OMML。",
            "InsertInlineTip" => "将当前 LaTeX 插入为 Word 行内公式。",
            "InsertDisplayTip" => "将当前 LaTeX 插入为居中的行间公式。",
            "InsertNumberedTip" => "将当前 LaTeX 插入为自动编号行间公式。",
            "ScreenshotOcrTip" => "等待下一次 LaTeXSnipper 全局快捷键截图；再次点击可取消。",
            "AutoNumberTip" => "为选中的 LaTeXSnipper 公式添加自动编号。",
            "RenumberTip" => "按文档顺序重排所有自动编号的 LaTeXSnipper 公式。",
            "HelpTip" => "显示 LaTeXSnipper Office 插件帮助。",
            "SettingsTip" => "配置 Office 插件快捷键说明和编号默认位置。",
            "ShowTaskPaneTip" => "显示 LaTeXSnipper 状态窗格。",
            "LoadSelectedTip" => "加载选中的 LaTeXSnipper 公式。",
            "DeleteSelectedTip" => "删除选中的 LaTeXSnipper 公式及其元数据。",
            "EditorInsert" => "插入",
            "EditorUpdate" => "更新",
            "Cancel" => "取消",
            "ErrorTitle" => "LaTeXSnipper",
            "SelectedFormulaRequired" => "请先选择一个 LaTeXSnipper 公式。",
            "SelectedFormulaMetadataMissing" => "无法找到所选公式的元数据。",
            "InsertInsideFormulaError" => "请将光标移到 LaTeXSnipper 公式外，再插入其他公式。",
            "InsertInsideNumberedFormulaError" => "请将光标移到带编号的 LaTeXSnipper 公式外，再插入其他公式。",
            "TaskPaneTitle" => "LaTeXSnipper",
            "TaskPaneActions" => "操作",
            "ReadyStatus" => "就绪。",
            "WorkingStatus" => "处理中...",
            "EditorReadyStatus" => "编辑器已就绪。",
            "ConvertingStatus" => "正在通过桌面端 Bridge 转换 LaTeX。",
            "InsertedStatus" => "已将公式插入 Word。",
            "UpdatedStatus" => "已更新 Word 公式。",
            "DeletedStatus" => "已删除所选公式。",
            "LoadedStatus" => "已加载所选公式。",
            "OcrWaitingStatus" => "正在等待截图识别；请使用全局快捷键后框选公式区域。",
            "OcrCanceledStatus" => "已取消截图识别。",
            "OcrLoadedStatus" => "截图识别结果已加载。",
            "AutoNumberedStatus" => "已为所选公式添加自动编号。",
            "RenumberedStatus" => "已重排 {count} 个公式编号。",
            "NoNumberedStatus" => "未找到自动编号公式。",
            "AlreadyNumberedStatus" => "所选公式已有编号。",
            "EditingFormulaTitle" => "正在编辑公式",
            "HelpStatus" => "已在 Word 中打开帮助。",
            "SettingsStatus" => "设置已打开。",
            "SettingsTitle" => "LaTeXSnipper Office 插件设置",
            "SettingsNumberingGroup" => "带编号公式默认布局",
            "SettingsNumberRight" => "编号在右侧",
            "SettingsNumberLeft" => "编号在左侧",
            "SettingsShortcuts" => "Ribbon KeyTip 快捷键\r\n- Alt, LS, I：行内公式。\r\n- Alt, LS, D：行间公式。\r\n- Alt, LS, N：带编号公式。\r\n- Alt, LS, O：截图识别。\r\n- Alt, LS, L：加载所选。\r\n- Alt, LS, X：删除所选。\r\n- Alt, LS, A：自动编号。\r\n- Alt, LS, R：重编号。\r\n- Alt, LS, P：状态窗格。\r\n- Alt, LS, S：设置。\r\n- Alt, LS, H：帮助。\r\n\r\n编辑器键盘\r\n- Ctrl+Enter：在编辑器中换行。\r\n- Esc：关闭编辑器且不应用更改。",
            "TaskPaneShownStatus" => "状态窗格已显示。",
            "ConnectedBridgeStatus" => "已连接到 LaTeXSnipper。",
            _ => key,
        };
    }
}
