"""Reproduce the pinned MathJax profiles from integrity-checked npm archives.

Use --archives DIR to rebuild; --verify checks vendored files without networking.
Neither ordinary application builds nor this script download dependencies.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path, PurePosixPath
import tarfile
from xml.sax.saxutils import escape

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
ASSETS = ROOT / "src/assets/MathJax"


def matches(path: str, patterns: list[str]) -> bool:
    return any(path == pattern or (
        pattern.endswith('/**') and path.startswith(pattern[:-2])
    ) for pattern in patterns)


def generated(manifest: dict, files: dict) -> dict[str, bytes]:
    config = {key: manifest[key] for key in ('version', 'defaultFont', 'fonts', 'extensions')}
    profiles = {
        name: sorted([path for path, item in files.items() if name in item['profiles']]
                     + ['config.js', 'runtime.js', 'office.js', 'resources.json'])
        for name in ('desktop', 'office')
    }
    digest = hashlib.sha256(json.dumps(manifest, sort_keys=True).encode()).hexdigest()
    resources = dict(version=manifest['version'], manifestSha256=digest, profiles=profiles, files=files)
    return {
        'config.js': ('// Generated by tools/mathjax/prepare.py.\n'
                      'globalThis.LaTeXSnipperMathJaxConfig = '
                      + json.dumps(config, separators=(',', ':')) + ';\n').encode(),
        'resources.json': (json.dumps(resources, indent=2) + '\n').encode(),
    }


def office_props(resources: dict) -> bytes:
    lines = ['<!-- Generated by tools/mathjax/prepare.py. -->', '<Project>', '  <ItemGroup>']
    for path in resources['profiles']['office']:
        path = escape(path)
        lines.append(f'    <Content Include="$(MSBuildThisFileDirectory)..\\..\\src\\assets\\MathJax\\{path}">'
                     f'<Link>MathJax/{path}</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>'
                     '<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory></Content>')
    lines.extend(['  </ItemGroup>', '</Project>', ''])
    return '\n'.join(lines).encode()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--archives', type=Path)
    parser.add_argument('--verify', action='store_true')
    args = parser.parse_args()
    manifest = json.loads((HERE / 'manifest.json').read_text())
    files = {}
    if args.archives:
        for package in manifest['packages']:
            archive = args.archives / package['archive']
            digest = base64.b64encode(hashlib.sha512(archive.read_bytes()).digest()).decode()
            if 'sha512-' + digest != package['integrity']:
                raise ValueError(f'Integrity mismatch: {archive}')
            with tarfile.open(archive) as tar:
                if package['name'] == 'mathjax':
                    data = tar.extractfile('package/adaptors/liteDOM.js').read()
                    (HERE / 'liteDOM.js').write_bytes(data)
                    manifest_digest = package['testAdaptorSha256']
                    if hashlib.sha256(data).hexdigest() != manifest_digest:
                        raise ValueError('Unexpected test adaptor')
                for member in tar.getmembers():
                    if not member.isfile() or not member.name.startswith('package/'):
                        continue
                    relative = member.name.removeprefix('package/')
                    if '..' in PurePosixPath(relative).parts:
                        raise ValueError(f'Unsafe archive path: {relative}')
                    common = matches(relative, package['common'])
                    if not common and not matches(relative, package['desktop']):
                        continue
                    path = str(PurePosixPath(package['destination']) / relative)
                    data = tar.extractfile(member).read()
                    target = ASSETS / path
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_bytes(data)
                    files[path] = dict(sha256=hashlib.sha256(data).hexdigest(),
                                       profiles=['desktop', 'office'] if common else ['desktop'])
        for name, content in generated(manifest, files).items():
            (ASSETS / name).write_bytes(content)
        (HERE / 'office.props').write_bytes(office_props(json.loads((ASSETS / 'resources.json').read_text())))
    elif not args.verify:
        parser.error('Specify --archives DIR or --verify')
    resources = json.loads((ASSETS / 'resources.json').read_text())
    if hashlib.sha256((HERE / 'liteDOM.js').read_bytes()).hexdigest() != manifest['packages'][0]['testAdaptorSha256']:
        raise ValueError('Test adaptor changed')
    for name, content in generated(manifest, resources['files']).items():
        if (ASSETS / name).read_bytes() != content:
            raise ValueError(f'Stale generated file: {name}')
    if (HERE / 'office.props').read_bytes() != office_props(resources):
        raise ValueError('Stale office.props')
    for path, item in resources['files'].items():
        if hashlib.sha256((ASSETS / path).read_bytes()).hexdigest() != item['sha256']:
            raise ValueError(f'Vendored file changed: {path}')
    actual = {str(p.relative_to(ASSETS)).replace('\\', '/') for p in ASSETS.rglob('*') if p.is_file()}
    expected = set(resources['profiles']['desktop'])
    if actual != expected:
        raise ValueError(f'Unexpected/missing assets: {actual ^ expected}')
    for name, paths in resources['profiles'].items():
        size = sum((ASSETS / path).stat().st_size for path in paths)
        print(f'{name}: {len(paths)} files, {size / 1024**2:.3f} MiB (MathJax {manifest["version"]})')


if __name__ == '__main__':
    main()
