"""Local MathJax conversion used by desktop export paths."""

from __future__ import annotations

import json
import time
import uuid
from typing import Any

from PyQt6.QtCore import QEventLoop, QThread, QTimer, QUrl
from PyQt6.QtWidgets import QApplication

from rendering.mathjax_runtime import ASSET_ROOT, loader_script


class MathJaxConversionError(RuntimeError):
    """Raised when the embedded MathJax conversion runtime fails."""


class _MathJaxConverter:
    def __init__(self) -> None:
        app = QApplication.instance()
        if app is None:
            raise MathJaxConversionError("MathJax export requires a running QApplication")
        if QThread.currentThread() is not app.thread():
            raise MathJaxConversionError("MathJax export must run on the UI thread")

        from PyQt6.QtWebEngineWidgets import QWebEngineView

        self._view = QWebEngineView()
        self._page = self._view.page()
        self._ready = False

    def convert(self, latex: str, outputs: tuple[str, ...]) -> dict[str, str]:
        self._ensure_ready()
        payload = json.dumps({"latex": latex, "outputs": outputs})
        request_id = json.dumps(uuid.uuid4().hex)
        self._run_javascript(
            f"LaTeXSnipperMathJax.start({request_id}, () => LaTeXSnipperMathJax.convert({payload}))"
        )
        try:
            deadline = time.monotonic() + 30
            while time.monotonic() < deadline:
                raw = self._run_javascript(f"LaTeXSnipperMathJax.take({request_id})")
                if raw:
                    result = json.loads(raw)
                    if result.get("error"):
                        raise MathJaxConversionError(result["error"])
                    for output in outputs:
                        prefix = "<math" if output == "mathml" else "<svg"
                        if not str(result.get(output, "")).startswith(prefix):
                            raise MathJaxConversionError(f"Invalid MathJax {output} result")
                    return {output: result[output] for output in outputs}
                self._pause()
            raise MathJaxConversionError("MathJax conversion timed out")
        finally:
            self._page.runJavaScript(f"LaTeXSnipperMathJax.cancel({request_id})")

    @staticmethod
    def _pause() -> None:
        loop = QEventLoop()
        QTimer.singleShot(25, loop.quit)
        loop.exec()

    def _ensure_ready(self) -> None:
        if self._ready:
            return
        loaded = self._wait_for_signal(
            self._page.loadFinished,
            lambda: self._page.setHtml(
                "<!doctype html><html><head>"
                + loader_script(output="svg", typeset=False, fallback=False)
                + "</head><body></body></html>", QUrl.fromLocalFile(str(ASSET_ROOT) + "/")),
            timeout_ms=15_000,
        )
        if not loaded:
            raise MathJaxConversionError("Failed to load the local MathJax export runtime")

        for _ in range(600):
            error = self._run_javascript("window.LaTeXSnipperMathJax && LaTeXSnipperMathJax.error")
            if error:
                raise MathJaxConversionError(str(error))
            if self._run_javascript("Boolean(window.LaTeXSnipperMathJax && LaTeXSnipperMathJax.ready)"):
                self._ready = True
                return
            self._pause()
        raise MathJaxConversionError("Local MathJax export runtime timed out")

    def _run_javascript(self, script: str) -> Any:
        result: list[Any] = []
        loop = QEventLoop()
        timer = QTimer()
        timer.setSingleShot(True)
        timer.timeout.connect(loop.quit)

        def completed(value: Any) -> None:
            result.append(value)
            loop.quit()

        self._page.runJavaScript(script, completed)
        timer.start(15_000)
        loop.exec()
        if timer.isActive():
            timer.stop()
        if not result:
            raise MathJaxConversionError("MathJax JavaScript execution timed out")
        return result[0]

    @staticmethod
    def _wait_for_signal(signal, start, *, timeout_ms: int) -> bool:
        result: list[bool] = []
        loop = QEventLoop()
        timer = QTimer()
        timer.setSingleShot(True)
        timer.timeout.connect(loop.quit)

        def completed(ok: bool) -> None:
            result.append(bool(ok))
            loop.quit()

        signal.connect(completed)
        try:
            timer.start(timeout_ms)
            start()
            loop.exec()
        finally:
            timer.stop()
            signal.disconnect(completed)
        return bool(result and result[0])


_converter: _MathJaxConverter | None = None
_last_key: tuple[str, tuple[str, ...]] | None = None
_last_result: dict[str, str] | None = None


def convert_latex_with_mathjax(latex: str, *, outputs: tuple[str, ...] = ("mathml", "svg")) -> dict[str, str]:
    """Return MathML and standalone SVG generated by the bundled MathJax."""
    global _converter, _last_key, _last_result
    source = str(latex or "")
    key = (source, outputs)
    if key == _last_key and _last_result is not None:
        return dict(_last_result)
    if _converter is None:
        _converter = _MathJaxConverter()
    result = _converter.convert(source, outputs)
    _last_key = key
    _last_result = dict(result)
    return result
